CREATE TABLE "GCG_4646_SHPFLRDATA1"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "ROLL_NO" INTEGER,
 "ROLL_WEIGHT" DOUBLE,
 "MEASURED_LAYFLAT" DOUBLE,
 "SMP_GM_WT" DOUBLE,
 "NIP_SPEED" INTEGER,
 "LBS_SCRAP" DOUBLE,
 "SCRAP_NOTE" VARCHAR(30),
 "LBS_ADDITIVE" DOUBLE,
 "ADDITIVE_TYPE" VARCHAR(100),
 "BLENDER_SETTING" VARCHAR(60),
 "GAUGE_BY_WEIGHT" DOUBLE,
 "ROLL_WEIGHT_WO_CORE" DOUBLE,
 "ROLL_FOOTAGE" DOUBLE,
 "LBS_PER_HOUR" DOUBLE,
 "LOG_TIME" TIMESTAMP DEFAULT NOW(),
 "CREATED_BY" CHAR(30),
 "MODIFIED_BY" CHAR(30),
 "FOOT_COUNT_OUT" DOUBLE);

 CREATE INDEX "GCG_4646_SFD1IX1" ON "GCG_4646_SHPFLRDATA1"("JOB", "SUFFIX", "SEQ", "ROLL_NO");