CREATE TABLE "GCG_4646_ADDLRTRINFO"(
 "ROUTER" CHAR(20),
 "TARGET_GAUGE" DOUBLE,
 "DIVISOR" DOUBLE,
 "LBS_PER_HOUR" DOUBLE,
 "TGT_ROLL_FOOTAGE" DOUBLE,
 "TGT_ROLL_WT" DOUBLE,
 "CORE_WT" DOUBLE,
 "CORE_SZ" DOUBLE,
 "ROLLS_PER_PALLET" INTEGER,
 "CREATED_BY" CHAR(30),
 "MODIFIED_BY" CHAR(30));
